package com.bayutb.baystoreapp.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00658E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2E)
val md_theme_light_secondary = Color(0xFF006C53)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF81F8D0)
val md_theme_light_onSecondaryContainer = Color(0xFF002117)
val md_theme_light_tertiary = Color(0xFF006B56)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7EF8D5)
val md_theme_light_onTertiaryContainer = Color(0xFF002018)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F26)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F26)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41484D)
val md_theme_light_outline = Color(0xFF71787E)
val md_theme_light_inverseOnSurface = Color(0xFFD9F6FF)
val md_theme_light_inverseSurface = Color(0xFF003641)
val md_theme_light_inversePrimary = Color(0xFF84CFFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00658E)
val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF84CFFF)
val md_theme_dark_onPrimary = Color(0xFF00344C)
val md_theme_dark_primaryContainer = Color(0xFF004C6C)
val md_theme_dark_onPrimaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_secondary = Color(0xFF63DBB5)
val md_theme_dark_onSecondary = Color(0xFF00382A)
val md_theme_dark_secondaryContainer = Color(0xFF00513E)
val md_theme_dark_onSecondaryContainer = Color(0xFF81F8D0)
val md_theme_dark_tertiary = Color(0xFF5FDBB9)
val md_theme_dark_onTertiary = Color(0xFF00382C)
val md_theme_dark_tertiaryContainer = Color(0xFF005140)
val md_theme_dark_onTertiaryContainer = Color(0xFF7EF8D5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F26)
val md_theme_dark_onBackground = Color(0xFFAEECFF)
val md_theme_dark_surface = Color(0xFF001F26)
val md_theme_dark_onSurface = Color(0xFFAEECFF)
val md_theme_dark_surfaceVariant = Color(0xFF41484D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(0xFF001F26)
val md_theme_dark_inverseSurface = Color(0xFFAEECFF)
val md_theme_dark_inversePrimary = Color(0xFF00658E)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF84CFFF)
val md_theme_dark_outlineVariant = Color(0xFF41484D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF00658E)


val SuccessIndicator = Color(0xFF92CE7C)
val FailedIndicator = Color(0xFFF50F3F)
val light_SuccessIndicator = Color(0xFF336B23)
val light_onSuccessIndicator = Color(0xFFFFFFFF)
val light_SuccessIndicatorContainer = Color(0xFFB3F39B)
val light_onSuccessIndicatorContainer = Color(0xFF032100)
val dark_SuccessIndicator = Color(0xFF98D781)
val dark_onSuccessIndicator = Color(0xFF073900)
val dark_SuccessIndicatorContainer = Color(0xFF1A520C)
val dark_onSuccessIndicatorContainer = Color(0xFFB3F39B)
val light_FailedIndicator = Color(0xFFBF002D)
val light_onFailedIndicator = Color(0xFFFFFFFF)
val light_FailedIndicatorContainer = Color(0xFFFFDAD9)
val light_onFailedIndicatorContainer = Color(0xFF410009)
val dark_FailedIndicator = Color(0xFFFFB3B2)
val dark_onFailedIndicator = Color(0xFF680014)
val dark_FailedIndicatorContainer = Color(0xFF920020)
val dark_onFailedIndicatorContainer = Color(0xFFFFDAD9)
